ratna = (input("Nama kamu siapa?"))
ratna = (input("Darimana asal  kamu Nalendra?"))
ratna = (input("Sebelumnya bersekolah dimana?"))
ratna = (input("hallo selamat siang Nalendra"))
ratna = (input("Wah dari Bekasi"))
ratna = (input("Pasti menyenangkan bersekolah di Sma 3 Babelan"))
